#!/bin/sh

tput() { command tput "$@" 2>/dev/null; }
attr() { tput AF "$1" || tput setaf "$1"; }
red() { attr 1; }
green() { attr 2; }
reset() { tput me || tput sgr0; }
die() { echo "$@"; exit 1; }

[ -x "$(command -v expect)" ] || die '"expect" is missing'

cargo build

sh_under_test="target/debug/rush"
sh_under_test=$(cd -P -- "$(dirname -- "$sh_under_test")" && echo "$(pwd -P)/$(basename -- "$sh_under_test")")

RUSH_DIR=$(dirname -- "$0")

# build helpers
for c in "$RUSH_DIR"/helpers/*.c; do
  exe="$RUSH_DIR"/helpers/"$(basename "$c" .c)"
  # shellcheck disable=SC2166,SC2039
  if [ ! -x "$exe" -o "$c" -nt "$exe" ]; then "$c"; fi
done

do_test() {
  test=$1
  if "$RUSH_DIR"/helpers/timeout 3 \
     "$RUSH_DIR"/helpers/harness.tcl "$test" "$sh_under_test" > /dev/null; then
    printf '%s%s%s\n' "$(green)" "$(basename "$test")" "$(reset)"
  else
    echo "$(red)$(basename "$test")$(reset)"
  fi
}

for t in tests/*.t; do
  do_test "$t"
done
